name: csb320-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - seaborn
  - matplotlib
  - ipython
  - pip
  - ipykernel